AtgTask1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('PublicChatRoom.urls')),
]

PublicChatRoom/urls.py
from django.urls import path
from . import views
app_name = 'chat'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('updateuser/<int:user_id>/', views.updateuser, name='updateuser'),
    path('searchuser/', views.searchuser, name='searchuser'),
    path('chatroom/', views.chatroom, name='chatroom'),


]

PublicChatRoom/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

class Message(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.author.username

    def last_20_messages(self):
        return Message.objetcts.order_by('-timestamp').all()[:20]

PublicChatRoom/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from simplemathcaptcha.fields import MathCaptchaField


#forms here
class UserCreationForm(UserCreationForm):
    captcha = MathCaptchaField()
    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2']

class UserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name','email')

PublicChatRoom/views.py
import json

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import UserCreationForm, UserChangeForm
from django.contrib.auth import authenticate, login, get_user_model
from django.utils.safestring import mark_safe
User = get_user_model()

# Create your views here.
@login_required()
def homepage(request):
    return render(request, 'PublicChatRoom/homepage.html')

def register(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect('/')
        else:
            render(request, 'registration/register.html', {'form':form})

    return render(request, 'registration/register.html', {'form':form})

@login_required()
def updateuser(request, user_id):
    user = get_object_or_404(get_user_model(), pk=user_id)
    form = UserChangeForm(request.POST, instance=user)
    if request.method =='POST':
        if form.is_valid():
            user = form.save()
            user.save()
            return redirect('/')
    return render(request, 'registration/update.html', {'form':form})

@login_required()
def searchuser(request):
    if request.method == 'POST':
        search_text = request.POST['search_text']
        users = User.objects.filter(username__contains=search_text)
        return render(request, 'registration/search.html',{'search_text':search_text, 'users':users})
    else:
        return render(request, 'registration/search.html')

@login_required()
def chatroom(request):
    return render(request, 'PublicChatRoom/chatroom.html', {
        'username': mark_safe(json.dumps(request.user.username)),
    })

templates/PublicChatRoom/chatroom.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Chatroom Page{% endblock %}



{% block content %}

    <div class="container-fluid text-light" align="center">

        <h1>Public Chatroom Page</h1><br>
        <textarea id="chat-log" cols="80" rows="20"></textarea><br>
        <label for="chat-message-input">Type Message Here-->>> </label><br>
        <input id="chat-message-input" type="text" size="80"><br><br>
        <input id="chat-message-submit" type="button" class="btn btn-success" value="Send Message"><br>
        <script>
            {% if user.is_authenticated %}
            var username = {{username}};
            {% endif %}

            var chatSocket = new WebSocket(
                'ws://'
                + window.location.host
                + '/ws/chat/chatroom/'
            );

            chatSocket.onmessage = function(e) {
                var data = JSON.parse(e.data);
                document.querySelector('#chat-log').value += (data.message +'---By---'+ data.username+ '\n');
            };

            chatSocket.onclose = function(e) {
                console.error('Chat socket closed unexpectedly');
            };

            document.querySelector('#chat-message-input').focus();
            document.querySelector('#chat-message-input').onkeyup = function(e) {
                if (e.keyCode === 13) {  // enter, return
                    document.querySelector('#chat-message-submit').click();
                }
            };

            document.querySelector('#chat-message-submit').onclick = function(e) {
                const messageInputDom = document.querySelector('#chat-message-input');
                const message = messageInputDom.value;

                chatSocket.send(JSON.stringify({
                    'username':username,
                    'message': message,
                }));
                messageInputDom.value = '';
            };
        </script>
    </div><br>

{% endblock %}

templates/PublicChatRoom/homepage.html
{% extends 'base.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}
    <div class="container-fluid text-light" align="center">
        <h1>Welcome to Homepage</h1><br>
        <script>
            document.querySelector('#room-name-submit').onclick = function(e) {
                window.location.pathname = '/chatroom/';
            };
        </script>
        <h2 class="bg-dark">You can see your details here</h2>
        <table class="table table-bordered text-light">
            <tr>
                <td align="right"><b>User ID : </b></td>
                <td>{{user.id}}</td>
            </tr>
            <tr>
                <td align="right"><b>Username : </b></td>
                <td>{{user.username}}</td>
            </tr>
            <tr>
                <td align="right"><b>First Name : </b></td>
                <td>{{user.first_name}}</td>
            </tr>
            <tr>
                <td align="right"><b>Last Name : </b></td>
                <td>{{user.last_name}}</td>
            </tr>
            <tr>
                <td align="right"><b>Email : </b></td>
                <td>{{user.email}}</td>
            </tr>
            <tr>
                <td align="right"><b>Joining Date : </b></td>
                <td>{{user.date_joined}}</td>
            </tr>
        </table>
        <a href="/updateuser/{{user.id}}" class="btn btn-primary">Edit you details</a>
    </div><br>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            {% if user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href="/admin/">GoTo AdminSite</a>
            </li>
            {% endif %}

            {% if user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link" type="submit" id="room-name-submit">Chat Room</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/accounts/logout">Logout</a>
            </li>
            <li class="nav-item text-light p-2">Logged As : {{user.username}}</li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="/accounts/login">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'chat:register' %}">Register</a>
            </li>
            {% endif %}
        </ul>

        {% if user.is_authenticated %}
        <form class="form-inline" method="post" action="/searchuser/">
            {% csrf_token %}
            <input class="form-control mr-sm-1" type="text" placeholder="Search User" name="search_text">
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
        {% endif %}



    </nav>

    {% block content %}
    {% endblock %}
    <footer class="bg-dark text-light p-4" align="center">
        <p>This web application is created by Lalkrishna Kothare for learning purpose only..</p>
    </footer>
</body>
</html>